/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DroneFlightLogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultPic: "Remote Pilot",
  unitSystem: "imperial",
  logFolderPath: "Drone Logs",
  filenameFormat: "YYYY-MM-DD - Flight - {{aircraft}} - {{location}}",
  autoOpenNote: true,
  fleet: [
    {
      id: "aircraft-1",
      make: "DJI",
      model: "Mavic 3 Enterprise",
      registration: "FA3X99001",
      serialNumber: "1581F4EKD22001"
    },
    {
      id: "aircraft-2",
      make: "Autel",
      model: "EVO II Pro 6K",
      registration: "FA3X99002",
      serialNumber: "AUTEL8899201"
    }
  ],
  batteries: [
    {
      id: "bat-1",
      batteryCode: "BAT-M3E-01",
      makeModel: "DJI Mavic 3 Intelligent Battery",
      totalCycles: 14,
      healthPct: 98
    },
    {
      id: "bat-2",
      batteryCode: "BAT-M3E-02",
      makeModel: "DJI Mavic 3 Intelligent Battery",
      totalCycles: 22,
      healthPct: 95
    },
    {
      id: "bat-3",
      batteryCode: "BAT-EVO-01",
      makeModel: "Autel EVO II Battery",
      totalCycles: 8,
      healthPct: 99
    }
  ]
};

// src/settings.ts
var import_obsidian = require("obsidian");
var DroneFlightLogSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F681} Drone Flight Log Settings" });
    containerEl.createEl("h3", { text: "General & Pilot Preferences" });
    new import_obsidian.Setting(containerEl).setName("Default Remote Pilot in Command (PIC)").setDesc("Pre-filled pilot name for new flight logs.").addText((text) => text.setPlaceholder("Pilot Name").setValue(this.plugin.settings.defaultPic).onChange(async (value) => {
      this.plugin.settings.defaultPic = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Measurement Units").setDesc("Select Imperial (ft/mph) or Metric (m/kmh) units for telemetry altitude and distance.").addDropdown((drop) => drop.addOption("imperial", "Imperial (feet, miles)").addOption("metric", "Metric (meters, km)").setValue(this.plugin.settings.unitSystem).onChange(async (value) => {
      this.plugin.settings.unitSystem = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Log Notes Vault Directory").setDesc("Folder path in your vault where flight logs will be saved.").addText((text) => text.setPlaceholder("Drone Logs").setValue(this.plugin.settings.logFolderPath).onChange(async (value) => {
      this.plugin.settings.logFolderPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Filename Pattern Template").setDesc("Variables available: YYYY-MM-DD, {{aircraft}}, {{location}}, {{purpose}}").addText((text) => text.setPlaceholder("YYYY-MM-DD - Flight - {{aircraft}} - {{location}}").setValue(this.plugin.settings.filenameFormat).onChange(async (value) => {
      this.plugin.settings.filenameFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-open Created Log Note").setDesc("Automatically open newly created flight log note in editor upon saving.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenNote).onChange(async (value) => {
      this.plugin.settings.autoOpenNote = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u{1F6F8} Aircraft Fleet Manager" });
    containerEl.createEl("p", { text: "Pre-configure your drone inventory for quick dropdown selection during logging.", cls: "setting-item-description" });
    const fleetContainer = containerEl.createDiv({ cls: "drone-settings-fleet-list" });
    this.renderFleetList(fleetContainer);
    new import_obsidian.Setting(containerEl).addButton((btn) => btn.setButtonText("+ Add New Aircraft").setCta().onClick(async () => {
      this.plugin.settings.fleet.push({
        id: `aircraft-${Date.now()}`,
        make: "DJI",
        model: "New Aircraft Model",
        registration: "N12345",
        serialNumber: "SN-00000"
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "\u{1F50B} Battery Inventory & Cycle Tracker" });
    const batteryContainer = containerEl.createDiv({ cls: "drone-settings-battery-list" });
    this.renderBatteryList(batteryContainer);
    new import_obsidian.Setting(containerEl).addButton((btn) => btn.setButtonText("+ Add New Battery").setCta().onClick(async () => {
      const newNum = this.plugin.settings.batteries.length + 1;
      this.plugin.settings.batteries.push({
        id: `bat-${Date.now()}`,
        batteryCode: `BAT-0${newNum}`,
        makeModel: "Intelligent Flight Battery",
        totalCycles: 0,
        healthPct: 100
      });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  renderFleetList(container) {
    container.empty();
    this.plugin.settings.fleet.forEach((aircraft, index) => {
      const row = container.createDiv({ cls: "drone-battery-item", attr: { style: "margin-bottom: 10px; display: flex; gap: 8px; flex-wrap: wrap; align-items: center;" } });
      const makeInp = row.createEl("input", { type: "text", cls: "drone-input", value: aircraft.make, placeholder: "Make (DJI)" });
      makeInp.style.width = "120px";
      makeInp.onchange = async (e) => {
        aircraft.make = e.target.value;
        await this.plugin.saveSettings();
      };
      const modelInp = row.createEl("input", { type: "text", cls: "drone-input", value: aircraft.model, placeholder: "Model (Mavic 3)" });
      modelInp.style.width = "180px";
      modelInp.onchange = async (e) => {
        aircraft.model = e.target.value;
        await this.plugin.saveSettings();
      };
      const regInp = row.createEl("input", { type: "text", cls: "drone-input", value: aircraft.registration, placeholder: "Registration #" });
      regInp.style.width = "120px";
      regInp.onchange = async (e) => {
        aircraft.registration = e.target.value;
        await this.plugin.saveSettings();
      };
      const delBtn = row.createEl("button", { cls: "drone-btn drone-btn-secondary", text: "\u{1F5D1}\uFE0F Delete" });
      delBtn.onclick = async () => {
        this.plugin.settings.fleet.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      };
    });
  }
  renderBatteryList(container) {
    container.empty();
    this.plugin.settings.batteries.forEach((bat, index) => {
      const row = container.createDiv({ cls: "drone-battery-item", attr: { style: "margin-bottom: 10px; display: flex; gap: 8px; flex-wrap: wrap; align-items: center;" } });
      const codeInp = row.createEl("input", { type: "text", cls: "drone-input", value: bat.batteryCode, placeholder: "Code (BAT-01)" });
      codeInp.style.width = "120px";
      codeInp.onchange = async (e) => {
        bat.batteryCode = e.target.value;
        await this.plugin.saveSettings();
      };
      const modelInp = row.createEl("input", { type: "text", cls: "drone-input", value: bat.makeModel, placeholder: "Battery Description" });
      modelInp.style.width = "180px";
      modelInp.onchange = async (e) => {
        bat.makeModel = e.target.value;
        await this.plugin.saveSettings();
      };
      const cycleInp = row.createEl("input", { type: "number", cls: "drone-input", value: String(bat.totalCycles), placeholder: "Cycles" });
      cycleInp.style.width = "80px";
      cycleInp.onchange = async (e) => {
        bat.totalCycles = Number(e.target.value);
        await this.plugin.saveSettings();
      };
      const delBtn = row.createEl("button", { cls: "drone-btn drone-btn-secondary", text: "\u{1F5D1}\uFE0F Delete" });
      delBtn.onclick = async () => {
        this.plugin.settings.batteries.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      };
    });
  }
};

// src/modals/FlightLogModal.ts
var import_obsidian3 = require("obsidian");

// src/utils/fileUtils.ts
var import_obsidian2 = require("obsidian");
function formatFlightLogMarkdown(data, settings) {
  const altUnit = settings.unitSystem === "imperial" ? "ft" : "m";
  const distUnit = settings.unitSystem === "imperial" ? "ft" : "m";
  const frontmatter = `---
type: drone-flight-log
tags:
  - drone/flight-log
  - aircraft/${data.aircraftModel.toLowerCase().replace(/[^a-z0-9]/g, "-")}
flight_date: "${data.flightDate}"
start_time: "${data.startTime}"
end_time: "${data.endTime}"
duration_minutes: ${data.durationMinutes}
location: "${data.location}"
coordinates: "${data.coordinates}"
purpose: "${data.purpose}"
aircraft_make: "${data.aircraftMake}"
aircraft_model: "${data.aircraftModel}"
aircraft_registration: "${data.aircraftRegistration}"
aircraft_serial: "${data.aircraftSerial}"
battery_ids:
${data.batteryIds.map((b) => `  - "${b}"`).join("\n")}
battery_start_pct: ${data.batteryStartPct}
battery_end_pct: ${data.batteryEndPct}
max_altitude_${altUnit}: ${data.maxAltitude}
max_distance_${distUnit}: ${data.maxDistance}
day_takeoffs: ${data.dayTakeoffs}
day_landings: ${data.dayLandings}
night_takeoffs: ${data.nightTakeoffs}
night_landings: ${data.nightLandings}
pic: "${data.pic}"
visual_observers:
${data.visualObservers.map((vo) => `  - "${vo}"`).join("\n")}
weather_wind: "${data.wind}"
weather_visibility: "${data.visibility}"
weather_temp: "${data.temperature}"
weather_lighting: "${data.lighting}"
has_anomalies: ${data.anomalies.trim().length > 0}
---

# \u{1F681} Drone Flight Log: ${data.aircraftModel} - ${data.flightDate}

> [!info] Flight Summary
> - **Date & Time**: ${data.flightDate} (${data.startTime} \u2013 ${data.endTime})
> - **Total Air Duration**: **${data.durationMinutes} minutes** (${(data.durationMinutes / 60).toFixed(1)} hrs)
> - **Location / Site**: ${data.location} ${data.coordinates ? `(\`${data.coordinates}\`)` : ""}
> - **Mission Purpose**: \`${data.purpose}\`
> - **Takeoffs & Landings**: Day (${data.dayTakeoffs}/${data.dayLandings}) | Night (${data.nightTakeoffs}/${data.nightLandings})

---

## \u{1F6F8} Aircraft & Battery Telemetry

| Parameter | Recorded Value |
| :--- | :--- |
| **Aircraft Model** | ${data.aircraftMake} ${data.aircraftModel} |
| **Registration / Serial** | \`${data.aircraftRegistration || "N/A"}\` / \`${data.aircraftSerial || "N/A"}\` |
| **Battery Unit(s)** | ${data.batteryIds.join(", ") || "N/A"} |
| **Battery Discharge** | ${data.batteryStartPct}% \u2192 ${data.batteryEndPct}% (Used ${data.batteryStartPct - data.batteryEndPct}%) |
| **Max Altitude** | ${data.maxAltitude} ${altUnit} AGL |
| **Max Distance** | ${data.maxDistance} ${distUnit} range |

---

## \u{1F464} Personnel & Weather Conditions

* **Remote Pilot in Command (PIC)**: [[${data.pic}]]
* **Visual Observers (VO)**: ${data.visualObservers.length > 0 ? data.visualObservers.map((vo) => `[[${vo}]]`).join(", ") : "None"}
* **Wind**: ${data.wind || "Calm"}
* **Visibility**: ${data.visibility || "Clear"}
* **Temperature**: ${data.temperature || "N/A"}
* **Lighting**: ${data.lighting || "Daylight"}
${data.weatherNotes ? `
> [!note] Weather Notes
> ${data.weatherNotes.split("\n").join("\n> ")}` : ""}

---

${data.anomalies.trim().length > 0 ? `> [!warning] Noteworthy Events & Anomalies
> ${data.anomalies.split("\n").join("\n> ")}

---` : ""}

## \u{1F4DD} Mission Log & Notes

${data.notes.trim() ? data.notes : "*No additional flight notes entered.*"}
`;
  return frontmatter;
}
function generateFilename(data, settings) {
  let template = settings.filenameFormat || "YYYY-MM-DD - Flight - {{aircraft}} - {{location}}";
  const cleanLocation = (data.location || "Site").replace(/[^a-zA-Z0-9 -]/g, "").trim();
  const cleanAircraft = (data.aircraftModel || "Drone").replace(/[^a-zA-Z0-9 -]/g, "").trim();
  let name = template.replace("YYYY-MM-DD", data.flightDate).replace("{{aircraft}}", cleanAircraft).replace("{{location}}", cleanLocation).replace("{{purpose}}", data.purpose);
  return `${name}.md`;
}
async function createFlightLogFile(app, data, settings) {
  const folderPath = (0, import_obsidian2.normalizePath)(settings.logFolderPath || "Drone Logs");
  if (!app.vault.getAbstractFileByPath(folderPath)) {
    await app.vault.createFolder(folderPath);
  }
  const filename = generateFilename(data, settings);
  let filePath = (0, import_obsidian2.normalizePath)(`${folderPath}/${filename}`);
  if (app.vault.getAbstractFileByPath(filePath)) {
    const timeSuffix = data.startTime.replace(":", "");
    const nameWithoutExt = filename.substring(0, filename.length - 3);
    filePath = (0, import_obsidian2.normalizePath)(`${folderPath}/${nameWithoutExt} (${timeSuffix}).md`);
  }
  const content = formatFlightLogMarkdown(data, settings);
  const file = await app.vault.create(filePath, content);
  return file;
}

// src/modals/FlightLogModal.ts
var FlightLogModal = class extends import_obsidian3.Modal {
  constructor(app, settings, onSaveSuccess) {
    super(app);
    this.activeTab = "mission";
    this.settings = settings;
    this.onSaveSuccess = onSaveSuccess;
    const now = /* @__PURE__ */ new Date();
    const todayStr = now.toISOString().split("T")[0];
    const hours = String(now.getHours()).padStart(2, "0");
    const mins = String(now.getMinutes()).padStart(2, "0");
    const defaultStartTime = `${hours}:${mins}`;
    const endNow = new Date(now.getTime() + 20 * 6e4);
    const endHours = String(endNow.getHours()).padStart(2, "0");
    const endMins = String(endNow.getMinutes()).padStart(2, "0");
    const defaultEndTime = `${endHours}:${endMins}`;
    const defaultAircraft = settings.fleet[0] || {
      make: "DJI",
      model: "Mavic 3 Enterprise",
      registration: "",
      serialNumber: ""
    };
    this.formData = {
      flightDate: todayStr,
      startTime: defaultStartTime,
      endTime: defaultEndTime,
      durationMinutes: 20,
      location: "Site Alpha",
      coordinates: "",
      purpose: "Commercial",
      dayTakeoffs: 1,
      dayLandings: 1,
      nightTakeoffs: 0,
      nightLandings: 0,
      aircraftMake: defaultAircraft.make,
      aircraftModel: defaultAircraft.model,
      aircraftRegistration: defaultAircraft.registration,
      aircraftSerial: defaultAircraft.serialNumber,
      batteryIds: settings.batteries.length > 0 ? [settings.batteries[0].batteryCode] : [],
      batteryStartPct: 100,
      batteryEndPct: 30,
      maxAltitude: settings.unitSystem === "imperial" ? 350 : 105,
      maxDistance: settings.unitSystem === "imperial" ? 1200 : 365,
      pic: settings.defaultPic || "Remote Pilot",
      visualObservers: [],
      wind: "8 mph NW",
      visibility: "10 miles",
      temperature: "72\xB0F",
      lighting: "Daylight",
      weatherNotes: "",
      anomalies: "",
      notes: ""
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("drone-flight-modal");
    const headerEl = contentEl.createDiv({ cls: "drone-modal-header" });
    const titleBox = headerEl.createDiv();
    const titleEl = titleBox.createDiv({ cls: "drone-modal-title" });
    titleEl.innerHTML = `<span class="drone-modal-title-icon">\u{1F681}</span> New Drone Flight Log`;
    titleBox.createDiv({ cls: "drone-modal-subtitle", text: "Record essential flight telemetry, equipment health, and mission details" });
    const tabsEl = contentEl.createDiv({ cls: "drone-modal-tabs" });
    this.createTabButton(tabsEl, "mission", "\u{1F4CD} Mission & Time");
    this.createTabButton(tabsEl, "equipment", "\u{1F6F8} Aircraft & Battery");
    this.createTabButton(tabsEl, "personnel", "\u{1F464} Crew & Weather");
    this.createTabButton(tabsEl, "notes", "\u26A0\uFE0F Anomalies & Notes");
    const bodyEl = contentEl.createDiv({ cls: "drone-modal-content" });
    this.renderMissionPane(bodyEl);
    this.renderEquipmentPane(bodyEl);
    this.renderPersonnelPane(bodyEl);
    this.renderNotesPane(bodyEl);
    const footerEl = contentEl.createDiv({ cls: "drone-modal-footer" });
    const cancelBtn = footerEl.createEl("button", { cls: "drone-btn drone-btn-secondary", text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const saveBtn = footerEl.createEl("button", { cls: "drone-btn drone-btn-primary", text: "Save Flight Log" });
    saveBtn.onclick = () => this.saveLog();
    const resizeHandle = footerEl.createDiv({ cls: "drone-resize-handle", text: "\u25E2" });
    resizeHandle.title = "Drag corner to resize window";
  }
  createTabButton(container, tabKey, label) {
    const btn = container.createEl("button", {
      cls: `drone-tab-button ${this.activeTab === tabKey ? "active" : ""}`,
      text: label
    });
    btn.onclick = () => {
      this.activeTab = tabKey;
      container.querySelectorAll(".drone-tab-button").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      const bodyEl = this.contentEl.querySelector(".drone-modal-content");
      if (bodyEl) {
        bodyEl.querySelectorAll(".drone-tab-pane").forEach((p) => p.classList.remove("active"));
        const activePane = bodyEl.querySelector(`.drone-tab-pane-${tabKey}`);
        if (activePane)
          activePane.classList.add("active");
      }
    };
  }
  calculateDuration() {
    if (!this.formData.startTime || !this.formData.endTime)
      return;
    const [sH, sM] = this.formData.startTime.split(":").map(Number);
    const [eH, eM] = this.formData.endTime.split(":").map(Number);
    if (!isNaN(sH) && !isNaN(sM) && !isNaN(eH) && !isNaN(eM)) {
      let startMin = sH * 60 + sM;
      let endMin = eH * 60 + eM;
      if (endMin < startMin) {
        endMin += 24 * 60;
      }
      this.formData.durationMinutes = endMin - startMin;
      const cardVal = this.contentEl.querySelector(".drone-duration-val");
      if (cardVal) {
        cardVal.textContent = `${this.formData.durationMinutes} minutes (${(this.formData.durationMinutes / 60).toFixed(1)} hrs)`;
      }
    }
  }
  renderMissionPane(container) {
    const pane = container.createDiv({ cls: `drone-tab-pane drone-tab-pane-mission ${this.activeTab === "mission" ? "active" : ""}` });
    const durCard = pane.createDiv({ cls: "drone-duration-card" });
    durCard.createDiv({ text: "Calculated Flight Air Duration", cls: "drone-field-label" });
    durCard.createDiv({ cls: "drone-duration-val", text: `${this.formData.durationMinutes} minutes (${(this.formData.durationMinutes / 60).toFixed(1)} hrs)` });
    const row1 = pane.createDiv({ cls: "drone-form-row-3" });
    const dateGrp = row1.createDiv({ cls: "drone-field-group" });
    dateGrp.createDiv({ cls: "drone-field-label", text: "Flight Date" });
    const dateInp = dateGrp.createEl("input", { type: "date", cls: "drone-input", value: this.formData.flightDate });
    dateInp.onchange = (e) => {
      this.formData.flightDate = e.target.value;
    };
    const startGrp = row1.createDiv({ cls: "drone-field-group" });
    startGrp.createDiv({ cls: "drone-field-label", text: "Start Time" });
    const startInp = startGrp.createEl("input", { type: "time", cls: "drone-input", value: this.formData.startTime });
    startInp.onchange = (e) => {
      this.formData.startTime = e.target.value;
      this.calculateDuration();
    };
    const endGrp = row1.createDiv({ cls: "drone-field-group" });
    endGrp.createDiv({ cls: "drone-field-label", text: "End Time" });
    const endInp = endGrp.createEl("input", { type: "time", cls: "drone-input", value: this.formData.endTime });
    endInp.onchange = (e) => {
      this.formData.endTime = e.target.value;
      this.calculateDuration();
    };
    const row2 = pane.createDiv({ cls: "drone-form-row" });
    const locGrp = row2.createDiv({ cls: "drone-field-group" });
    locGrp.createDiv({ cls: "drone-field-label", text: "Location / Launch Site" });
    const locInp = locGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.location, placeholder: "e.g. Site Alpha / 123 Main St" });
    locInp.onchange = (e) => {
      this.formData.location = e.target.value;
    };
    const gpsGrp = row2.createDiv({ cls: "drone-field-group" });
    gpsGrp.createDiv({ cls: "drone-field-label", text: "GPS Coordinates (Optional)" });
    const gpsInp = gpsGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.coordinates, placeholder: "37.7749, -122.4194" });
    gpsInp.onchange = (e) => {
      this.formData.coordinates = e.target.value;
    };
    const row3 = pane.createDiv({ cls: "drone-form-row" });
    const purpGrp = row3.createDiv({ cls: "drone-field-group" });
    purpGrp.createDiv({ cls: "drone-field-label", text: "Flight Purpose" });
    const purpSel = purpGrp.createEl("select", { cls: "drone-select" });
    ["Commercial", "Training", "Mapping", "Recreational", "Inspection", "Search & Rescue"].forEach((p) => {
      const opt = purpSel.createEl("option", { value: p, text: p });
      if (p === this.formData.purpose)
        opt.selected = true;
    });
    purpSel.onchange = (e) => {
      this.formData.purpose = e.target.value;
    };
    const row4 = pane.createDiv({ cls: "drone-form-row-3" });
    this.createNumberField(row4, "Day Takeoffs", this.formData.dayTakeoffs, (v) => this.formData.dayTakeoffs = v);
    this.createNumberField(row4, "Day Landings", this.formData.dayLandings, (v) => this.formData.dayLandings = v);
    this.createNumberField(row4, "Night Takeoffs", this.formData.nightTakeoffs, (v) => this.formData.nightTakeoffs = v);
    this.createNumberField(row4, "Night Landings", this.formData.nightLandings, (v) => this.formData.nightLandings = v);
  }
  renderEquipmentPane(container) {
    const pane = container.createDiv({ cls: `drone-tab-pane drone-tab-pane-equipment ${this.activeTab === "equipment" ? "active" : ""}` });
    const row1 = pane.createDiv({ cls: "drone-form-row" });
    const craftGrp = row1.createDiv({ cls: "drone-field-group" });
    craftGrp.createDiv({ cls: "drone-field-label", text: "Select Aircraft" });
    const craftSel = craftGrp.createEl("select", { cls: "drone-select" });
    this.settings.fleet.forEach((craft) => {
      const opt = craftSel.createEl("option", {
        value: craft.id,
        text: `${craft.make} ${craft.model} (${craft.registration || "No Reg"})`
      });
      if (craft.model === this.formData.aircraftModel)
        opt.selected = true;
    });
    craftSel.onchange = (e) => {
      const selectedCraft = this.settings.fleet.find((f) => f.id === e.target.value);
      if (selectedCraft) {
        this.formData.aircraftMake = selectedCraft.make;
        this.formData.aircraftModel = selectedCraft.model;
        this.formData.aircraftRegistration = selectedCraft.registration;
        this.formData.aircraftSerial = selectedCraft.serialNumber;
      }
    };
    const batGrp = row1.createDiv({ cls: "drone-field-group" });
    batGrp.createDiv({ cls: "drone-field-label", text: "Battery Unit Code" });
    const batInp = batGrp.createEl("input", {
      type: "text",
      cls: "drone-input",
      value: this.formData.batteryIds.join(", "),
      placeholder: "e.g. BAT-M3E-01"
    });
    batInp.onchange = (e) => {
      this.formData.batteryIds = e.target.value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
    };
    const row2 = pane.createDiv({ cls: "drone-form-row" });
    this.createNumberField(row2, "Start Charge %", this.formData.batteryStartPct, (v) => this.formData.batteryStartPct = v);
    this.createNumberField(row2, "End Charge %", this.formData.batteryEndPct, (v) => this.formData.batteryEndPct = v);
    const altUnit = this.settings.unitSystem === "imperial" ? "ft" : "m";
    const distUnit = this.settings.unitSystem === "imperial" ? "ft" : "m";
    const row3 = pane.createDiv({ cls: "drone-form-row" });
    this.createNumberField(row3, `Max Altitude (${altUnit} AGL)`, this.formData.maxAltitude, (v) => this.formData.maxAltitude = v);
    this.createNumberField(row3, `Max Distance from Controller (${distUnit})`, this.formData.maxDistance, (v) => this.formData.maxDistance = v);
  }
  renderPersonnelPane(container) {
    const pane = container.createDiv({ cls: `drone-tab-pane drone-tab-pane-personnel ${this.activeTab === "personnel" ? "active" : ""}` });
    const row1 = pane.createDiv({ cls: "drone-form-row" });
    const picGrp = row1.createDiv({ cls: "drone-field-group" });
    picGrp.createDiv({ cls: "drone-field-label", text: "Remote Pilot in Command (PIC)" });
    const picInp = picGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.pic });
    picInp.onchange = (e) => {
      this.formData.pic = e.target.value;
    };
    const voGrp = row1.createDiv({ cls: "drone-field-group" });
    voGrp.createDiv({ cls: "drone-field-label", text: "Visual Observers (Comma Separated)" });
    const voInp = voGrp.createEl("input", {
      type: "text",
      cls: "drone-input",
      value: this.formData.visualObservers.join(", "),
      placeholder: "e.g. Jane Doe, John Smith"
    });
    voInp.onchange = (e) => {
      this.formData.visualObservers = e.target.value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
    };
    const row2 = pane.createDiv({ cls: "drone-form-row" });
    const windGrp = row2.createDiv({ cls: "drone-field-group" });
    windGrp.createDiv({ cls: "drone-field-label", text: "Wind Speed & Direction" });
    const windInp = windGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.wind, placeholder: "e.g. 8 mph NW" });
    windInp.onchange = (e) => {
      this.formData.wind = e.target.value;
    };
    const visGrp = row2.createDiv({ cls: "drone-field-group" });
    visGrp.createDiv({ cls: "drone-field-label", text: "Visibility" });
    const visInp = visGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.visibility, placeholder: "e.g. 10 statute miles" });
    visInp.onchange = (e) => {
      this.formData.visibility = e.target.value;
    };
    const row3 = pane.createDiv({ cls: "drone-form-row" });
    const tempGrp = row3.createDiv({ cls: "drone-field-group" });
    tempGrp.createDiv({ cls: "drone-field-label", text: "Temperature" });
    const tempInp = tempGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.temperature, placeholder: "e.g. 72\xB0F" });
    tempInp.onchange = (e) => {
      this.formData.temperature = e.target.value;
    };
    const lightGrp = row3.createDiv({ cls: "drone-field-group" });
    lightGrp.createDiv({ cls: "drone-field-label", text: "Lighting / Sky" });
    const lightInp = lightGrp.createEl("input", { type: "text", cls: "drone-input", value: this.formData.lighting, placeholder: "Daylight / Clear" });
    lightInp.onchange = (e) => {
      this.formData.lighting = e.target.value;
    };
    const wNotesGrp = pane.createDiv({ cls: "drone-field-group" });
    wNotesGrp.createDiv({ cls: "drone-field-label", text: "Additional Weather Observations" });
    const wNotesTa = wNotesGrp.createEl("textarea", { cls: "drone-textarea", placeholder: "e.g. Light turbulence near tree line, clear horizon" });
    wNotesTa.value = this.formData.weatherNotes;
    wNotesTa.onchange = (e) => {
      this.formData.weatherNotes = e.target.value;
    };
  }
  renderNotesPane(container) {
    const pane = container.createDiv({ cls: `drone-tab-pane drone-tab-pane-notes ${this.activeTab === "notes" ? "active" : ""}` });
    const anomGrp = pane.createDiv({ cls: "drone-field-group" });
    anomGrp.createDiv({ cls: "drone-field-label", text: "\u26A0\uFE0F Noteworthy Events / Anomalies / Incidents" });
    anomGrp.createDiv({ cls: "drone-field-hint", text: "Log any firmware errors, GPS compass warnings, battery alerts, or near-misses" });
    const anomTa = anomGrp.createEl("textarea", { cls: "drone-textarea", placeholder: "e.g. Brief compass interference prompt on takeoff, cleared after elevation increase." });
    anomTa.value = this.formData.anomalies;
    anomTa.onchange = (e) => {
      this.formData.anomalies = e.target.value;
    };
    const notesGrp = pane.createDiv({ cls: "drone-field-group" });
    notesGrp.createDiv({ cls: "drone-field-label", text: "\u{1F4DD} Mission Notes & Objectives Achieved" });
    const notesTa = notesGrp.createEl("textarea", { cls: "drone-textarea", placeholder: "Captured 45 aerial photos of North Ridge mapping grid. Flight path stable." });
    notesTa.value = this.formData.notes;
    notesTa.onchange = (e) => {
      this.formData.notes = e.target.value;
    };
  }
  createNumberField(container, label, initialVal, onChange) {
    const grp = container.createDiv({ cls: "drone-field-group" });
    grp.createDiv({ cls: "drone-field-label", text: label });
    const inp = grp.createEl("input", { type: "number", cls: "drone-input", value: String(initialVal) });
    inp.onchange = (e) => {
      onChange(Number(e.target.value));
    };
  }
  async saveLog() {
    try {
      const file = await createFlightLogFile(this.app, this.formData, this.settings);
      new import_obsidian3.Notice(`Flight Log saved: ${file.basename}`);
      if (this.settings.autoOpenNote) {
        const leaf = this.app.workspace.getUnpinnedLeaf();
        await leaf.openFile(file);
      }
      if (this.onSaveSuccess) {
        this.onSaveSuccess();
      }
      this.close();
    } catch (err) {
      new import_obsidian3.Notice(`Error saving flight log: ${err}`);
      console.error(err);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/DashboardView.ts
var import_obsidian4 = require("obsidian");

// src/utils/statsUtils.ts
async function parseVaultFlightStats(app) {
  const stats = {
    totalFlights: 0,
    totalDurationMinutes: 0,
    totalDayLandings: 0,
    totalNightLandings: 0,
    incidentCount: 0,
    aircraftHours: {},
    batteryUsage: {},
    recentFlights: []
  };
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const cache = app.metadataCache.getFileCache(file);
    const fm = cache?.frontmatter;
    if (!fm)
      continue;
    const isFlightLog = fm.type === "drone-flight-log" || Array.isArray(fm.tags) && fm.tags.includes("drone/flight-log");
    if (!isFlightLog)
      continue;
    stats.totalFlights += 1;
    const duration = Number(fm.duration_minutes || 0);
    stats.totalDurationMinutes += duration;
    stats.totalDayLandings += Number(fm.day_landings || 0);
    stats.totalNightLandings += Number(fm.night_landings || 0);
    if (fm.has_anomalies || fm.anomalies && String(fm.anomalies).trim().length > 0) {
      stats.incidentCount += 1;
    }
    const aircraft = String(fm.aircraft_model || "Unknown Aircraft");
    stats.aircraftHours[aircraft] = (stats.aircraftHours[aircraft] || 0) + duration;
    const batIds = Array.isArray(fm.battery_ids) ? fm.battery_ids : [];
    for (const bId of batIds) {
      if (bId) {
        stats.batteryUsage[bId] = (stats.batteryUsage[bId] || 0) + 1;
      }
    }
    stats.recentFlights.push({
      file,
      date: String(fm.flight_date || file.basename),
      aircraft,
      location: String(fm.location || "N/A"),
      duration,
      purpose: String(fm.purpose || "General"),
      hasAnomalies: Boolean(fm.has_anomalies)
    });
  }
  stats.recentFlights.sort((a, b) => b.date.localeCompare(a.date));
  return stats;
}

// src/views/DashboardView.ts
var DRONE_DASHBOARD_VIEW_TYPE = "drone-flight-dashboard-view";
var DroneFlightDashboardView = class extends import_obsidian4.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    this.settings = settings;
  }
  getViewType() {
    return DRONE_DASHBOARD_VIEW_TYPE;
  }
  getDisplayText() {
    return "Drone Flight Dashboard";
  }
  getIcon() {
    return "plane";
  }
  async onOpen() {
    await this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("drone-dashboard-container");
    const headerEl = container.createDiv({ cls: "drone-dashboard-header" });
    const title = headerEl.createDiv({ cls: "drone-dashboard-title" });
    title.innerHTML = `<span>\u{1F6F8}</span> Drone Flight Analytics & Fleet Command`;
    const btnGroup = headerEl.createDiv({ cls: "drone-btn-group" });
    const newLogBtn = btnGroup.createEl("button", { cls: "drone-btn drone-btn-primary", text: "+ Log New Flight" });
    newLogBtn.onclick = () => {
      new FlightLogModal(this.app, this.settings, () => this.render()).open();
    };
    const refreshBtn = btnGroup.createEl("button", { cls: "drone-btn drone-btn-secondary", text: "\u{1F504} Refresh" });
    refreshBtn.onclick = () => this.render();
    const stats = await parseVaultFlightStats(this.app);
    const grid = container.createDiv({ cls: "drone-metrics-grid" });
    const totalHoursStr = (stats.totalDurationMinutes / 60).toFixed(1);
    this.createMetricCard(grid, "\u23F1\uFE0F", "Total Flight Time", `${totalHoursStr} hrs`, `${stats.totalDurationMinutes} minutes in air`);
    this.createMetricCard(grid, "\u{1F4CA}", "Total Flights", `${stats.totalFlights}`, `${stats.recentFlights.length} logged notes`);
    this.createMetricCard(grid, "\u{1F305}", "Landings (Day / Night)", `${stats.totalDayLandings} / ${stats.totalNightLandings}`, "Regulatory takeoff tracking");
    this.createMetricCard(grid, "\u26A0\uFE0F", "Anomalies & Incidents", `${stats.incidentCount}`, stats.incidentCount === 0 ? "Clean safety record" : "Review safety logs");
    const split = container.createDiv({ cls: "drone-dashboard-split" });
    const leftCol = split.createDiv({ cls: "drone-section-card" });
    const recentHeader = leftCol.createDiv({ cls: "drone-section-header" });
    recentHeader.createSpan({ text: "\u{1F4CB} Recent Flight Logs" });
    if (stats.recentFlights.length === 0) {
      leftCol.createDiv({ text: 'No drone flights logged yet. Click "+ Log New Flight" above to record your first mission!', cls: "drone-field-hint" });
    } else {
      const table = leftCol.createEl("table", { cls: "drone-flight-table" });
      const thead = table.createEl("thead");
      const trHead = thead.createEl("tr");
      trHead.createEl("th", { text: "Date" });
      trHead.createEl("th", { text: "Aircraft" });
      trHead.createEl("th", { text: "Location" });
      trHead.createEl("th", { text: "Duration" });
      trHead.createEl("th", { text: "Purpose" });
      const tbody = table.createEl("tbody");
      stats.recentFlights.slice(0, 10).forEach((item) => {
        const tr = tbody.createEl("tr");
        tr.style.cursor = "pointer";
        tr.onclick = () => {
          this.app.workspace.getUnpinnedLeaf().openFile(item.file);
        };
        tr.createEl("td", { text: item.date });
        tr.createEl("td", { text: item.aircraft });
        tr.createEl("td", { text: item.location });
        tr.createEl("td", { text: `${item.duration}m` });
        const purpTd = tr.createEl("td");
        const purpClass = item.purpose.toLowerCase();
        purpTd.createEl("span", { cls: `drone-tag drone-tag-${purpClass}`, text: item.purpose });
      });
    }
    const rightCol = split.createDiv({ cls: "drone-section-card" });
    const rightHeader = rightCol.createDiv({ cls: "drone-section-header" });
    rightHeader.createSpan({ text: "\u{1F50B} Fleet & Battery Inventory" });
    rightCol.createDiv({ cls: "drone-field-label", text: "Aircraft Flight Hours" });
    Object.entries(stats.aircraftHours).forEach(([craft, mins]) => {
      const row = rightCol.createDiv({ cls: "drone-battery-item" });
      row.createDiv({ cls: "drone-battery-id", text: craft });
      row.createDiv({ cls: "drone-battery-cycles", text: `${(mins / 60).toFixed(1)} hrs (${mins}m)` });
    });
    rightCol.createDiv({ cls: "drone-field-label", text: "Configured Battery Pool" });
    this.settings.batteries.forEach((bat) => {
      const row = rightCol.createDiv({ cls: "drone-battery-item" });
      const uses = stats.batteryUsage[bat.batteryCode] || 0;
      const totalC = bat.totalCycles + uses;
      row.createDiv({ cls: "drone-battery-id", text: bat.batteryCode });
      row.createDiv({ cls: "drone-battery-cycles", text: `${totalC} cycles | Health: ${bat.healthPct}%` });
    });
  }
  createMetricCard(container, icon, label, value, subtext) {
    const card = container.createDiv({ cls: "drone-metric-card" });
    card.createDiv({ cls: "drone-metric-icon", text: icon });
    card.createDiv({ cls: "drone-metric-label", text: label });
    card.createDiv({ cls: "drone-metric-value", text: value });
    card.createDiv({ cls: "drone-metric-subtext", text: subtext });
  }
  async onClose() {
  }
};

// src/main.ts
var DroneFlightLogPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      DRONE_DASHBOARD_VIEW_TYPE,
      (leaf) => new DroneFlightDashboardView(leaf, this.settings)
    );
    this.addSettingTab(new DroneFlightLogSettingTab(this.app, this));
    this.addRibbonIcon("plane", "Log Drone Flight", () => {
      new FlightLogModal(this.app, this.settings).open();
    });
    this.addCommand({
      id: "log-drone-flight",
      name: "Log New Drone Flight",
      callback: () => {
        new FlightLogModal(this.app, this.settings).open();
      }
    });
    this.addCommand({
      id: "open-drone-dashboard",
      name: "Open Drone Flight Dashboard",
      callback: () => {
        this.activateDashboardView();
      }
    });
    this.addCommand({
      id: "insert-drone-flight-template",
      name: "Insert Flight Log Template into Active Note",
      editorCallback: (editor) => {
        const defaultAircraft = this.settings.fleet[0] || {
          make: "DJI",
          model: "Mavic 3 Enterprise",
          registration: "FA3X99001",
          serialNumber: "SN12345678"
        };
        const now = /* @__PURE__ */ new Date();
        const templateStr = formatFlightLogMarkdown({
          flightDate: now.toISOString().split("T")[0],
          startTime: "10:00",
          endTime: "10:25",
          durationMinutes: 25,
          location: "Site Location",
          coordinates: "",
          purpose: "Commercial",
          dayTakeoffs: 1,
          dayLandings: 1,
          nightTakeoffs: 0,
          nightLandings: 0,
          aircraftMake: defaultAircraft.make,
          aircraftModel: defaultAircraft.model,
          aircraftRegistration: defaultAircraft.registration,
          aircraftSerial: defaultAircraft.serialNumber,
          batteryIds: this.settings.batteries.length > 0 ? [this.settings.batteries[0].batteryCode] : ["BAT-01"],
          batteryStartPct: 100,
          batteryEndPct: 35,
          maxAltitude: this.settings.unitSystem === "imperial" ? 400 : 120,
          maxDistance: this.settings.unitSystem === "imperial" ? 1500 : 450,
          pic: this.settings.defaultPic || "Remote Pilot",
          visualObservers: [],
          wind: "5 mph N",
          visibility: "10 statute miles",
          temperature: "68\xB0F",
          lighting: "Daylight",
          weatherNotes: "",
          anomalies: "",
          notes: "Flight mission notes here..."
        }, this.settings);
        editor.replaceSelection(templateStr);
        new import_obsidian5.Notice("Inserted Drone Flight Log Template");
      }
    });
    console.log("Drone Flight Log Plugin loaded successfully.");
  }
  async activateDashboardView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(DRONE_DASHBOARD_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false) || workspace.getUnpinnedLeaf();
      if (leaf) {
        await leaf.setViewState({
          type: DRONE_DASHBOARD_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("Drone Flight Log Plugin unloaded.");
  }
};
